apiVersion: batch/v1
kind: Job
metadata:
  name: model-api-init
spec:
  template:
    metadata:
      name: model-api-init
    spec:
      containers:
        - name: model-init
          image: kind-registry:5000/model-api:latest
          imagePullPolicy: IfNotPresent
          command: ["python3", "download_models.py"]
          envFrom:
          - secretRef:
              name: env-secrets
          resources:
            limits:
              cpu: "500m"
              memory: "3Gi"
          volumeMounts:
          - name: llm-shared-volume
            mountPath: /mnt/llm-shared-volume
      restartPolicy: Never
      volumes:
      - name: llm-shared-volume        
        hostPath:
          path: /mnt/models/data
          type: DirectoryOrCreate
