apiVersion: v1
kind: PersistentVolume
metadata:
  name: warehouse-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual 
  local:
    path: /mnt/data/hive-warehouse
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values: 
          - platform-control-plane