apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: warehouse-pvc
  namespace: hive
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: manual 
  resources:
    requests:
      storage: 1Gi
