version: '3.8'

services:
  datahub-postgres:
    image: postgres:16
    env_file:
      - .env.datahub
    volumes:
      - platform-datahub-postgres-data:/var/lib/postgresql/data
    networks:
      - kind
volumes:
  platform-datahub-postgres-data:

networks:
  kind:
    external: true
    name: kind
