apiVersion: v1
kind: PersistentVolume
metadata:
  name: jupyter-notebook-pv
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /opt/jupyter/notebooks
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jupyter-notebook-pvc
  namespace: jupyter
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName:  jupyter-notebook-pv
  storageClassName: standard