kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
containerdConfigPatches:
- |- 
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."kind-registry:5000"]
    endpoint = ["http://kind-registry:5000"]
nodes:
- role: control-plane
  kubeadmConfigPatches:
  - |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
  extraPortMappings:
  - containerPort: 80
    hostPort: 8080
    protocol: TCP
  - containerPort: 30081
    hostPort: 8081
    protocol: TCP
  - containerPort: 30082
    hostPort: 8082
    protocol: TCP
  - containerPort: 30083
    hostPort: 8083
    protocol: TCP
  - containerPort: 30084
    hostPort: 8084
    protocol: TCP
  - containerPort: 30888
    hostPort: 8888
    protocol: TCP
  - containerPort: 30901
    hostPort: 9001
    protocol: TCP
  extraMounts: # host >> container(control plane). Then map to pods through airflow helm chart
  - hostPath: services/airflow/dags
    containerPath: /opt/airflow/dags
  - hostPath: services/airflow/spark_scripts
    containerPath: /opt/airflow/spark_scripts
  - hostPath: services/airflow/lib
    containerPath: /opt/airflow/lib
  - hostPath: services/airflow/include
    containerPath: /opt/airflow/include
  - hostPath: services/jupyter/notebooks
    containerPath: /opt/jupyter/notebooks
  - hostPath: services/models/data
    containerPath: /data/llm
  - hostPath: services/minio/data
    containerPath: /opt/minio/data