apiVersion: v1
kind: Service
metadata:
  name: trino-svc
  namespace: trino
  labels:
    app: trino
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30082
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: coordinator
    app.kubernetes.io/instance: trino
    app.kubernetes.io/name: trino
