apiVersion: v1
kind: Service
metadata:
  name: datahub-svc
  namespace: datahub
  labels:
    app: datahub
spec:
  type: NodePort
  ports:
    - port: 9002
      targetPort: 9002
      nodePort: 30084
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/instance: datahub
    reapp.kubernetes.io/name: datahub-frontend
