apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-dag-pv
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: /opt/airflow/dags
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-lib-pv
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: /opt/airflow/lib
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-spark-pv
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: /opt/airflow/spark_scripts
  storageClassName: standard