apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-dag-pv
  labels:
    type: local
    app: airflow
spec:
  capacity:
    storage: 128Mi
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: /mnt/airflow/dags
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-lib-pv
  labels:
    type: local
    app: airflow
spec:
  capacity:
    storage: 128Mi
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: /mnt/airflow/lib
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-spark-pv
  labels:
    type: local
    app: airflow
spec:
  capacity:
    storage: 128Mi
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: /mnt/airflow/spark_scripts
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-include-pv
  labels:
    type: local
    app: airflow
spec:
  capacity:
    storage: 128Mi
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: /mnt/airflow/include
  storageClassName: standard