apiVersion: apps/v1
kind: Deployment
metadata:
  name: hive-metastore
  namespace: hive
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hive-metastore
  template:
    metadata:
      labels:
        app: hive-metastore
    spec:   
      containers:
      - name: hive-metastore
        image: kind-registry:5000/custom-apache-hive:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9083
        env:
        - name: SERVICE_NAME
          value: metastore
        envFrom:
        - secretRef:
            name: hive-secrets
        resources:
          limits:
            cpu: "1"
            memory: "2Gi"
        volumeMounts:
        - name: hive-config-volume
          mountPath: /mnt/hive-config
      volumes:
      - name: hive-config-volume
        configMap:
          name: hive-config