apiVersion: v1
kind: Service
metadata:
  name: trino-svc
  namespace: trino
  labels:
    app: trino
spec:
  type: NodePort
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30081
      protocol: TCP
      name: http
  selector:
    app: trino
    release: trino
    component: coordinator