apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter
  namespace: jupyter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jupyter
  template:
    metadata:
      labels:
        app: jupyter
    spec:
      containers:
      - name: jupyter
        image: kind-registry:5000/custom-spark-jupyter:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8888
        resources:
          limits:
            cpu: "300m"
            memory: "2Gi"
        volumeMounts:
        - name: jupyter-pvc-volume
          mountPath: /opt/spark/notebooks
        envFrom:
        - secretRef:
            name: env-secrets
      volumes:
      - name: jupyter-pvc-volume
        persistentVolumeClaim:
          claimName: jupyter-notebook-pvc