apiVersion: v1
kind: ServiceAccount
metadata:
  name: jupyter-service-account
  namespace: jupyter
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jupyter-role
  namespace: jupyter
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "persistentvolumeclaims"]
  verbs: ["create", "get", "list", "watch", "delete", "update", "deletecollection", 'patch']

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jupyter-role-binding
  namespace: jupyter
subjects:
- kind: ServiceAccount
  name: jupyter-service-account
  namespace: jupyter
roleRef:
  kind: Role
  name: jupyter-role
  apiGroup: rbac.authorization.k8s.io
