apiVersion: v1
kind: Service
metadata:
  name: jupyter-svc
  namespace: jupyter
  labels:
    app: jupyter
spec:
  type: NodePort
  ports:
    - port: 8888
      targetPort: 8888
      nodePort: 30083
      protocol: TCP
      name: http
  selector:
    app: jupyter 