apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-dag-pv
  labels:
    type: local
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadOnlyMany
  hostPath:
    path: /opt/airflow/dags
  storageClassName: standard