apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-dag-pvc
  namespace: airflow
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
  volumeName: airflow-dag-pv
  storageClassName: standard

