config:
   webserver:
      base_url: http://localhost/airflow

# 
# https://airflow.apache.org/docs/helm-chart/stable/production-guide.html#webserver-secret-key
webserverSecretKeySecretName: airflow-webserver-secret


secret: 
   - envName: "AIRFLOW_CONN_MINIO_DEFAULT"
     secretName: "minio-connnection"
     secretKey: "minio-connnection-key"
   - envName: "AIRFLOW_CONN_KAGGLE_DEFAULT"
     secretName: "kaggle-connnection"
     secretKey: "kaggle-connnection-key"

# https://github.com/airflow-helm/charts/blob/main/charts/airflow/docs/faq/monitoring/log-persistence.md
scheduler:
  logCleanup:
    ## WARNING: scheduler log-cleanup must be disabled if `logs.persistence.enabled` is `true`
    enabled: false

workers:
  logCleanup:
    ## WARNING: workers log-cleanup must be disabled if `logs.persistence.enabled` is `true`
    enabled: false

logs:
  ## NOTE: this is the default value
  path: /opt/airflow/logs
  
  persistence:
    enabled: true

    ## NOTE: set `storageClass` to "" for the cluster-default
    storageClass: "default"
    
    ## NOTE: some types of StorageClass will ignore this request (for example, EFS)
    size: 5Gi
    
    ## WARNING: as multiple pods will write logs, this MUST be ReadWriteMany
    accessMode: ReadWriteMany