version: '3.8'

services:  
  
  postgresql:
    image: postgres:16
    hostname: postgresql
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "conduktor-platform"
      POSTGRES_USER: "conduktor"
      POSTGRES_PASSWORD: "some_password"
      POSTGRES_HOST_AUTH_METHOD: "scram-sha-256"
    networks:
      - kind

  conduktor-platform:
    image: conduktor/conduktor-platform:latest
    ports:
      - "8090:8080"
    volumes:
      - conduktor_data:/var/conduktor
    env_file:
      - .env.conduktor
    networks:
      - kind

volumes:
  pg_data: {}
  conduktor_data: {}

networks:
  kind:
    external: true
    name: kind
